# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Some noise
author: 
  name: Christopher A. Pattison
  email: cpattison@berkeley.edu
# logo: /assets/img/headshot.png
description: >- # this means to ignore newlines until "baseurl:"
  A blog on various aspects of quantum error correction and fault-tolerance.


# Build settings
# Use remote-theme plugin to load `minima` repository. But first, ensure the `theme` key is disabled.
# theme: minima
remote_theme: "jekyll/minima"

plugins:
  - jekyll-feed
  - jekyll-remote-theme

# markdown: kramdown
# mathjax: true

minima:
  skin: auto
  date_format: "%b %d, %Y"
  social_links:
    - icon: bluesky
      title: Bluesky
      url: "https://bsky.app/profile/chris-pattison.bsky.social"
    - icon: google-scholar
      title: "Google Scholar"
      url: "https://scholar.google.com/citations?user=4neYf8oAAAAJ&hl=en"
    - icon: github
      title: Github
      url: "https://github.com/ChrisPattison"

